export class Client{
    _id:string;
    role:string;
    is_verified:boolean;
    country:string;
    email:string;
    password:string;
    first_name:string;
    last_name:string;
    permission_level:number;
    contact_number:string;
    nic:string;
    address:string;
    avatar_url:string;
    registered_at:Date;
    relations:[{
        nic:string;
        first_name:string,
        last_name:string,
        dob:Date;
        relationship:string;
        contact_number:string;
        gender:string;
    }]
}